name: bank_stack

services:
  nginx:
    image: nginx:alpine
    depends_on:
      php:
        condition: service_started    
    ports:
      - "8080:80"         
    restart: unless-stopped
    volumes:
      - ./app/public:/var/www/public:ro
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - app_network                

  php:
    build:
      context: ./docker/php
    volumes:
      - ./app:/var/www:rw
    networks:
      - app_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - ./.data/postgres:/var/lib/postgresql/data
    # ports:
    #   - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app_network            

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    networks:
      - app_network

networks:
  app_network:                      
    driver: bridge